# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67724cb7ba86b46067a46303ce3f3dbda11f729f2e54e5c91d6ccceaafa4509de5d448e768aca3e8ddff61b880347df5236574292ffc8fa24f656a27ad112835

test:
  secret_key_base: 14220864aae881fef792c2958dd26b6088affa1bed109cf28645e1568fd8703bdda1f55b6616002a28729af5d6586068531a16423363264aa2941f7755bd5694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
